version: "3.0"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - .docker/db:/var/run/postgresql/data
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: ${PWD}/.docker/django/Dockerfile
    volumes:
      - .:/home/vicsite/app/
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    restart: always
    ports:
      - 8000:8000

  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .docker/nginx:/etc/nginx/conf.d/:ro
      - .docker/certbot/www:/var/www/certbot/:ro
    env_file:
      - .env
    depends_on:
      - api
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - .docker/certbot/www/:/var/www/certbot/:ro

volumes:
  postgres_data:


networks:
  default:
    external:
      name: nginx-proxy
